# Generated by Django 4.1.3 on 2022-12-06 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='ingresar nombre director', max_length=50)),
                ('FechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Películas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Título', models.CharField(help_text='ingresar nombre película', max_length=64)),
                ('AñoLanzamiento', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Buscador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Id único', primary_key=True, serialize=False)),
                ('Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DirectoresCine.directores')),
                ('Película', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DirectoresCine.películas')),
            ],
        ),
    ]
